name: systetica
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  sqflite: ^2.0.0+4
  dio: ^4.0.4
  http: ^0.13.4
  url_launcher: ^6.0.17
  flutter_localizations:
    sdk: flutter
  mask_text_input_formatter: ^2.0.0
  email_validator: ^2.0.1
  cpf_cnpj_validator: ^2.0.0
  responsive_grid: ^2.0.0
  intl: ^0.17.0
  dropdown_search: ^3.0.1
  flutter_animator: ^3.2.2
  page_transition: ^2.0.9
  form_field_validator: ^1.1.0
  animated_text_kit:
  image_picker:
  image_cropper:
  dropdown_button2:


flutter:
  uses-material-design: true
  assets:
    - assets/img/cabelereiro-inicio.png
    - assets/img/alterar-senha.png
    - assets/img/gerar-codigo.png
    - assets/img/login.png
    - assets/img/registro.png
    - assets/img/ativar-usuario.png